Fix #41: Option to include non-workable display area in `getWindowBoundsCentered`
sindresorhus/electron-util pull request #44
Opened 2021-03-13 21:03 UTC by lacymorrow

This allows for centered windows to ignore the space taken by the Windows taskbar or the MacOS dock so that programs can accurately be centered.

2021-03-13 21:05 UTC, lacymorrow commented
@sindresorhus not sure what you would like to call it but I think `includeFullDisplayBounds` is better than `includeNonworkableArea`

2021-03-17 08:55 UTC, sindresorhus commented
Maybe `useFullBounds`?

2021-03-17 08:55 UTC, sindresorhus requested changes

2021-03-17 08:55 UTC, sindresorhus commented on index.js
> +		api.screen.getDisplayNearestPoint(api.screen.getCursorScreenPoint()).workArea;
There's a lot of duplication here. Extract `api.screen.getDisplayNearestPoint(api.screen.getCursorScreenPoint())` to a variable.

2021-03-17 08:55 UTC, sindresorhus commented
You also need to update `index.d.ts`.

2021-03-17 08:56 UTC, sindresorhus commented on readme.md
> +Use the full display size when calculating the position. By default only the workable screen area is used, which excludes the Windows taskbar and MacOS dock.
```suggestion
Use the full display size when calculating the position. By default, only the workable screen area is used, which excludes the Windows taskbar and macOS dock.
```

2021-03-22 23:57 UTC, lacymorrow commented
Ready for another review

2021-03-24 13:53 UTC, sindresorhus commented on index.d.ts
> +	```
?

2021-03-24 13:53 UTC, sindresorhus commented on index.d.ts
> +	Default: `false`
```suggestion
	@default false
```

2021-03-24 13:53 UTC, sindresorhus commented on index.d.ts
> +	Use the full display size when calculating the position, rather than just the workable area.
The description here and the readme should be the same.

I think it's useful to explain what the "workable" area is.

2021-03-24 13:54 UTC, sindresorhus commented
You have a lint violation.

2021-03-27 16:08 UTC, lacymorrow commented
Fixed up

2021-04-06 15:56 UTC, merged